%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 720
image_height: 540
distortion_parameters:
   k1: -0.04217
   k2: -0.00413
   p1: 0.00179
   p2: -0.00063
projection_parameters:
   fx: 352.779
   fy: 354.609
   cx: 359.035
   cy: 260.546
